#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8
  customize: !include customize.yaml
  packages: !include_dir_merge_named configuration/package



updater:
  reporting: false
sun:
conversation:
config:
person:
system_health:
mobile_app:


#################################################################
## Components
#################################################################

tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret darksky_apikey
    mode: daily
    name: "Winkel"


#################################################################
## Includes
#################################################################

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml